### ISSUE TITLE
RNASeq on WCDT OHSU cell lines

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/core-operations#42] opened 2016-05-21 03:57 UTC
A placeholder for line 6:

https://docs.google.com/spreadsheets/d/1vTQJzJrcZ4ekU-2Fo5h8IqdbNy2YB-WylS47TtTVFTU/edit?usp=sharing

Details TBD by @melissacline (and ticket name changed, click edit).

WXS with 28+ samples.

**Comment by briandoconnor** [comment] 2016-05-21 05:13
Potential issue on this one that Melissa has asked Jeltje about is the request for CNAs as well as mutations.  Not sure we have a tool/workflow to accommodate the former.

**Comment by briandoconnor** [comment] 2016-05-24 18:42
@melissacline reports we need to have the submitter provide the data.  Upload/transfer of data has not happened as of today.

**Comment by melissacline** [comment] 2016-05-25 03:25
The data has been transferred to medbook-ftp and is under /data/ftp/kinca.  In order to read the files, I need to get added to the ftp group.  I've asked Erich to add me.

**Comment by melissacline** [comment] 2016-05-25 22:39
Hi Jeltje,
The data is on  pod at /pod/pstore/projects/production/wcdt.  There is one subdirectory per sample, with individual fastq files.  They are _not_ paired end.  John has a trick for faking out the pipeline for non-paired-end analysis.

**Comment by Jeltje** [comment] 2016-05-25 23:45
Have asked @jvivian for details, waiting for response.

**Comment by Jeltje** [comment] 2016-05-26 00:44
@melissacline Not sure where to put inputs and outputs. I'm assuming inputs still go, encrypted,  in cgl-driver-projects-encrypted/wcdt ? But should the output be encrypted now that we use the subscriber pays system? If so, where should I put these (cgl-driver-projects is not encrypted)?

**Comment by melissacline** [comment] 2016-05-26 01:12
FWIW, this is cell line data and doesn't strictly need to be encrypted.
But I suggest we keep the inputs in cgl-driver-projects-encrypted/wcdt
anyway, just for consistency.  It's a nice simplification for us if input
data is always under the encrypted bucket.

The outputs definitely don't need to be encrypted.  So, let's put them
in cgl-driver-projects/wcdt.
The RNASeq output is small enough that I'll live dangerously and say that
we don't have to worry about setting subscriber-pays.  These aren't
FASTQs.  And that way, when the data's ready, we can generate a list of
URLs to give to Ted and Teo as a means of output data delivery.

**Comment by Jeltje** [comment] 2016-05-26 01:25
Excellent, thanks. I've tarred the files and got the info I needed from John. I will proceed to upload to cgl-driver-projects-encrypted/wcdt/oicr_issue42_input

**Comment by Jeltje** [comment] 2016-05-26 17:48
Files uploaded. Could not install cgcloud on stacker so moved to the VM. Trying to get a cluster set up, having some trouble with permissions.

**Comment by Jeltje** [comment] 2016-05-27 03:11
Debugged with Hannes. Now creating a new master image (takes a while), then should be ready to start up a cluster.

**Comment by briandoconnor** [comment] 2016-05-27 16:07
Hi @Jeltje do you think this analysis will be setup and running before the long weekend?  I'd like to give clients a heads up by the end of today.  Thanks

**Comment by Jeltje** [comment] 2016-05-27 16:18
I have learned the hard way not to make promises, but I will report back around noon. It is my top priority.

**Comment by Jeltje** [comment] 2016-05-27 20:53
The problem isn't fixed. Running on stacker is not really an option because the docker container takes over the whole system (limiting cpus doesn't work as expected). We will have to continue next week.

**Comment by jvivian** [comment] 2016-05-27 20:59
Jeltje, can you please open an issue and assign it to me?

**Comment by briandoconnor** [comment] 2016-05-28 01:11
Moved @Jeltje to an AWS host to act as her launcher host (no more openstack in the equation) and refreshed her keys.  That seemed to solve the ssh key problem.

**Comment by Jeltje** [comment] 2016-05-28 03:09
@john, I created your issue at https://github.com/BD2KGenomics/cgl-docker-lib/issues/120

**Comment by briandoconnor** [comment] 2016-05-28 22:54
@Jeltje gave a quick update, she's still having SSH issues but has queued 7 of the 35+ RNASeq samples for running on stacker.

**Comment by Jeltje** [comment] 2016-05-29 18:30
Six of seven finished, one crashed. The crash left a jobStore directory, which made the next batch crash automatically. Renamed jobStore, started next batch of 7 (of 32, not 35+).

**Comment by Jeltje** [comment] 2016-05-31 05:44
Jobs don't finish.
https://github.com/BD2KGenomics/cgl-docker-lib/issues/121

**Comment by Jeltje** [comment] 2016-05-31 16:13
Started VM, connected without problems, now setting up cgcloud and dependencies.
For future reference:
```
sudo apt-get update
sudo apt-get install python-pip
sudo apt-get install python-virtualenv
sudo apt-get install libffi-dev
sudo apt-get install libyaml-dev
sudo apt-get install python-dev
sudo apt-get install libssl-dev
virtualenv cgcloud
source cgcloud/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools
pip install pycrypto
pip install cgcloud-core
pip install cgcloud-toil
```

**Comment by Jeltje** [comment] 2016-05-31 17:14
Stuck on https://github.com/BD2KGenomics/cgl-docker-lib/issues/122

**Comment by Jeltje** [comment] 2016-05-31 17:48
Solved, now at
https://github.com/BD2KGenomics/cgl-docker-lib/issues/123

**Comment by Jeltje** [comment] 2016-06-01 03:19
Samples are now running on a toil cluster at AWS

**Comment by Jeltje** [comment] 2016-06-01 15:58
25 of 32 samples finished correctly. The remaining 7 seem to have been wrongly diagnosed as paired end, probably due to fastq naming. Looking into this.

**Comment by Jeltje** [comment] 2016-06-01 20:19
Fastqs renamed by taking out all underscores, rerun started

**Comment by Jeltje** [comment] 2016-06-02 02:12
Rerun finished, all samples OK.

**Comment by briandoconnor** [comment] 2016-06-02 04:21
Hi @melissacline I ping'd the PIs to let them know data is on the way.  Thanks much @Jeltje !

**Comment by melissacline** [comment] 2016-06-02 06:23
Bravo all!  I've sent off the list of URLs.

**Comment by briandoconnor** [comment] 2016-06-02 17:06
@melissacline can you close the ticket?

**Closed** 2016-06-02 18:55 UTC
Labels: analysis

**Comment by melissacline** [comment] 2016-06-03 02:24
From the collaborator's entry in the spreadsheet:

We are interested in tumor/normal comparison of pre- and post-enzalutamide treated patient samples.  We would like to see CNAs and mutations.  Directed analysis around AR is of particular interest.  I have also submitted a request for RNAseq analysis of this sample set (though it seems that not all samples will have both data types available).

Please feel free to contact me with questions.
Thanks!
Laura
503-346-4617

High priority samples
DTB-024
DTB-060
DTB-063
DTB-063Pro
DTB-073
DTB-073Pro
DTB-080
DTB-080Pro
DTB-089
DTB-089Pro
DTB-098
DTB-102
DTB-111
DTB-111Pro
DTB-127
DTB-128
DTB-129
DTB-135Pro
DTB-135
DTB-077Pro
DTB-127Pro
DTB-141
DTB-149
DTB-103
DTB-022Pro2
DTB-115Pro
DTB-096
DTB-099
DTB-115

Additional samples that may have WES available:
DTB-024Pro
DTB-137
DTB-077
DTB-096Pro
DTB-119
DTB-022Pro
DTB-099Pro
DTB-130
DTB-130ProX
DTB-134
DTB-134Pro
DTB-024Pro2
DTB-128Pro
DTB-141Pro
DTB-149Pro
DTB-098Pro
DTB-102Pro
DTB-119Pro
DTB-137Pro
DTB-194
DTB-194Pro
DTB-129Pro
DTB-022
DTB-060Pro
DTB-103Pro
DTB-130ProB
