### ISSUE TITLE
RNASeq on WCDT OICR cell lines/<pending>

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/core-operations#41] opened 2016-05-21 03:54 UTC
A placeholder for line 5:

https://docs.google.com/spreadsheets/d/1vTQJzJrcZ4ekU-2Fo5h8IqdbNy2YB-WylS47TtTVFTU/edit?usp=sharing

Details TBD by @melissacline (and ticket name changed, click edit).

RNASeq with 35+ samples.

**Comment by melissacline** [comment] 2016-05-24 01:14
Status: Paul appears to have analyzed 30 of the 32 samples (see https://github.com/BD2KGenomics/core-operations/issues/20).  However, some of the files are suspiciously small, suggesting that the input data was incomplete.  Carly King (Carly King <kinca@ohsu.edu>) confirms that these small sizes are strange.  We are expecting new input files.

**Comment by melissacline** [comment] 2016-05-26 04:48
Duplicate of 42

**Closed** 2016-05-26 04:49 UTC
Labels: analysis, duplicate
